VIA_ENABLE = yes
VIAL_ENABLE = yes

OLED_ENABLE = yes
RGB_MATRIX_ENABLE = no

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

MOUSEKEY_ENABLE		= no
QMK_SETTINGS		= no
COMBO_ENABLE		= no
KEY_OVERRIDE_ENABLE	= no
CAPS_WORD_ENABLE	= no
LAYER_LOCK_ENABLE	= no
REPEAT_KEY_ENABLE	= no
SPACE_CADET_ENABLE	= no
TAP_DANCE_ENABLE	= no
TRI_LAYER_ENABLE	= no
GRAVE_ESC_ENABLE	= no
MAGIC_ENABLE		= no

#CONVERT_TO = rp2040_ce
